name: "Build Debug"

on: [push, pull_request]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up environment
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
          echo $FIREBASE_SERVICE_ACCOUNT_JSON > ./firebase-service-account.json
          chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: App Distribution
        run: ./gradlew appDistributionUploadDebug
