name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-34-jdk17

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/abonity/abonity/app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
