name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-34-jdk17

    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
